refactor: using OOP
ShcherbakovVS/mesto-project pull request #1
Opened 2023-06-21 21:22 UTC by ShcherbakovVS

2023-06-22 10:23 UTC, antonmishchenkov requested changes
Хорошая работа, так держать! Код аккуратен и читабелен.
Есть ряд замечаний, которые необходимо исправить, чтобы работу можно было принять. Все они отмечены как "Надо исправить".

Успехов на второй итерации!

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/utils/constant.js
> +export const adding = document.querySelector('.profile__add');
**Надо исправить:**

Переменные принято называть существительными. 
Следует исправить названия **всех подобных переменных**, чтобы они начинались с существительного и не обозначали продолжительность действия. Были более конкретными в названии. 

Например, для данной: ```popupProfileOpenButton```

Аналогично для переменной ниже

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Api.js
> +    _getResponseData(res) {
**Отлично:**

Отлично, что обработка ответа от сервера вынесена в отдельный метод

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Card.js
> +                    if (res.likes.some((like) => {
**Надо исправить:**

Нам нет необходимости осуществлять данную проверку, так как действие происходит в блоке `then` для api запроса, а это значит, что если выполнение кода дошло до этого места, значит от сервера пришел успешный ответ, что значит что мы можем смело осуществлять соответствующую DOM логику.

Следует удалить проверку здесь и на строке 56

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Card.js
> +                        evt.target.classList.add('elements__like_actived');
**Надо исправить:**

DOM установку/удаление лайка карточке следует вынести в отдельный публичный метод/методы класса Card, чтобы была возможность переиспользовать их логику обособленно от слушателей:

```
likeCard(count) {
     this._element.querySelector('.elements__like').classList.add('elements__like_actived');
     this._like.textContent = count;
}
```

Аналогично для удаления

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/FormValidator.js
> +        const inputList = Array.from(formElement.querySelectorAll(objSelectors.inputSelector));
**Надо исправить:**

Список полей формы и кнопку сабмита необходимо вынести в конструктор класса в качестве полей, чтобы не искать элементы внутри метода и не передавать их в другие методы. 
Необходимо для того, чтобы доступ к этим статичным элементам формы был во всем классе.

```
this._form = ...
this._inputList = ...
```

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Popup.js
> +        document.removeEventListener('keydown', this._handleEscClose.bind(this));
**Надо исправить:**

Привязку метода к контексту через `bind` следует выполнить единоразово в конструкторе класса

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/PopupForRemoving.js
> +        this.cardForRemoving = '';
**Надо исправить:**

Логика класса должна быть абстрактна, то есть необходимо избегать привязки к логике конкретных сущностей (в данном случае к сущности карточки), чтобы мы могли переиспользовать логику класса для подтверждения любых действий, а не только действия удаления карточки.

Следует сделать рефакторинг класса и заменить все вхождения слова `card` на более абстрактные, например, `item`

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/PopupWithImage.js
> +        this._popupElement.querySelector('.popup__title-place').textContent = title;
**Надо исправить:**

В родительском классе присутствует поле `this.popupElement`, а не `this._popupElement`. Следует заменить здесь

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Selector.js
> +export default class Selector {
**Надо исправить:**

Название класса должно соответствовать его логике. Следует переименовать в `Section`

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/UserInfo.js
> +        return this._userDataReceivingAPI()
**Надо исправить:**

Класс UserInfo должен описывать только DOM логику информации пользователя. Всю серверную логику следует выполнять в файле `index.js`.

То есть метод `getUserInfo` должен просто возвращать объект текущих значений имени, профессии и аватара пользователя со страницы, а метод `setUserInfo` должен устанавливать значения в эти же поля на основе аргументов, которые мы ему передаем.

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +            popups.removing.cardForRemoving.remove();
**Надо исправить:**

DOM удаление карточки следует вынести в отдельный публичный метод класса Card и вызывать его здесь для текущего удаляемого экземпляра

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +            userInfo.avatarElement.src = res.avatar;
**Надо исправить:**

DOM установку аватара пользователю следует осуществлять с помощью метода класса UserInfo, так как данный функционал логически относится к сущности пользователя

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +            popups.imageUpdate._formContainer.reset();
**Надо исправить:**

Если поле или метод используется вне своего класса, то его следует сделать публичным

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +            document.querySelector(cardListSection).prepend(cardElement);
**Надо исправить:**

Добавление новых карточек в контейнер необходимо осуществлять с помощью метода `addItem` для экземпляра класса Section, который должен быть доступен во всем файле, так как контейнер карточек - статичный элемент страницы в единственном экземпляре (см. замечание на строке 106)

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +        userInfo.avatarElement.src = info.avatar;
Аналогично замечанию на строке 52

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +        const cardList = new Selector({
**Надо исправить:**

Создание данного экземпляра следует вынести в global scope файла, либо в global scope создать перезаписываемую переменную, которой потом в данном месте присвоить значение контейнера, чтобы затем далее использовать ее при добавлении новых карточек

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +                const card = new Card(item, '#template-card', (image, title) => {
**Надо исправить:**

Чтобы не дублировать код, создание карточки следует вынести в отдельную функцию

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +    const formValid = new FormValidator(objSelectors, form);
**Надо исправить:**

Инстанцирование экземпляров класса FormValidator и активация валидации для них должны осуществляться для каждой формы отдельно в global scope, чтобы доступ к экземплярам класса был во всем файле, а не только в области видимости данной функции.
То есть для каждой формы должен существовать свой именованный экземпляр.

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +Promise.all([api.getDataUser(), api.getInitialCards()])
**Отлично:**

Отлично, что используется `Promise.all`

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Card.js
> +
**Надо исправить:**

После перезагрузки страницы теряется информация о том, какие карточки были пролайканы текущим пользователем

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/components/Card.js
> +            this._handleImageClick();
**Надо исправить:**

При открытии попапа изображения в консоли браузера возникает ошибка, нет возможности открыть попап.

2023-06-22 10:23 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +        })
**Надо исправить:**

При сабмите формы добавления карточки также необходимо деактивировать кнопку сабмита, иначе после добавления карточки и последующего повторного открытия формы - кнопка активна - в результате чего есть возможность сделать сабмит с пустыми невалидными полями

2023-06-22 20:47 UTC, ShcherbakovVS commented on src/scripts/pages/index.js
> +            popups.imageUpdate._formContainer.reset();
Здесь обращение к полю в своем классе

2023-06-22 21:46 UTC, ShcherbakovVS commented on src/scripts/pages/index.js
> +    const formValid = new FormValidator(objSelectors, form);
Оставил прежнюю логику, но добавляю экземпляры валидаторов в поля нового объекта

2023-06-26 10:42 UTC, antonmishchenkov requested changes
Отлично, работа стала лучше! Еще несколько замечаний, и ее можно будет принять.

Прошу прощения за длительную проверку.

2023-06-26 10:42 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +        const cardList = new Section({
**Некорректно исправлено замечание.**

Таким образом мы все еще создаем два экземпляра Section для одного и того же контейнера (здесь и на строке 16). Следует объявить переменную на строке 16 через `let`, чтобы она была перезаписываемой, а на текущей строчке выполнить переприсваивание (убрать `const`)

2023-06-26 10:42 UTC, antonmishchenkov commented on src/scripts/components/UserInfo.js
> +        return this._userDataUpdatingAPI(name, about);
**Надо исправить:**

Метод `setUserInfo` - это сэттер, он не должен возвращать никакое значение. Он должен устанавливать некоторые данные в поля класса. Следует удалить данную строчку. К тому же текущая реализация все еще реализует логику обращения к серверу, что некорректно, так как класс UserInfo должен работать только с DOM

2023-06-26 10:42 UTC, antonmishchenkov commented on src/scripts/pages/index.js
> +    userInfo.setUserInfo(inputValues.forename, inputValues.description)
**Надо исправить:**

Исходя из замечания в классе UsrInfo, здесь следует выполнять `api` запрос к серверу на установку данных пользователя и только в его блоке `then` ниже уже вызывать DOM логику - `userInfo.setUserInfo`

2023-06-27 15:04 UTC, antonmishchenkov approved these changes
Отлично, замечания исправлены, работа принимается.
Успехов в дальнейших проектах!

2023-06-27 15:23 UTC, merged